source 'https://rubygems.org'
ruby '2.3.1'
gem 'rspec', '~> 3.5.0'
gem 'rake'
gem 'faker'
gem 'selenium-webdriver'
gem 'twilio-ruby', '~> 4.11', '>= 4.11.1'
gem 'rest-client'
gem 'rack', '1.6.4'
gem 'pry'
gem 'awesome_print'
